name: Spring Boot Build and verify Sonar

on:
  workflow_call:
    inputs:
      SONAR_PROJECT_KEY:
        required: true
        type: string
      ARTIFACT_NAME:
        required: true
        type: string
      ARTIFACT_PATH:
        required: true
        type: string
      CREATE_ARTIFACT:
        required: false
        type: boolean
        default: true
      EXTRA_ARTIFACT:
        required: false
        default: false
        type: boolean
      EXTRA_ARTIFACT_NAME:
        required: false
        type: string
      EXTRA_ARTIFACT_PATH:
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build, test and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.SONAR_PROJECT_KEY }}

      - name: Build and run test
        run: mvn clean package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.1
        if: inputs.CREATE_ARTIFACT == true
        with:
          name: ${{ inputs.ARTIFACT_NAME }}
          path: ${{ inputs.ARTIFACT_PATH }}
          retention-days: 1

      - name: Upload Extra Artifacts
        uses: actions/upload-artifact@v4.3.1
        if: inputs.EXTRA_ARTIFACT == true
        with:
          name: ${{ inputs.EXTRA_ARTIFACT_NAME }}
          path: ${{ inputs.ARTIFACT_PATH }}
          retention-days: 1